Repository milieuinfo/webcomponent-vl-ui-alert, pull requests merged in 2019-08, with the labels that each got.

#6 vl-ui-core versie 1.4.3: define nodig in demo
  package.json
Labels: dependencies

#9 UIG-179:vl-alert met buttons
  demo/demo.css
  demo/demo.css.map
  demo/vl-alert.html
  package-lock.json
  package.json
  style.css
  style.css.map
  test/vl-alert.test.html
  vl-alert.src.js
Labels: feature

#10 Merge branch 'master' of https://github.com/milieuinfo/webcomponent-vl-ui-alert into UIG-179
  demo/vl-alert.html
  test/vl-alert.test.html
  vl-alert.src.js
Labels: enhancement

#11 UIG-179 defensief programmeren om null problemen te voorkomen
  vl-alert.src.js
Labels: bug

#12 Configure Renovate
  renovate.json
Labels: enhancement

#17 Verwijder Dockerfile
  .dockerignore
  Dockerfile
Labels: chore

#18 Verwijder dependabot config
  .dependabot/config.yml
Labels: chore

#19 Voeg link naar release notes toe aan documentatie
  vl-alert.src.js
Labels: chore

#15 Update dependency vl-ui-icon to v2.0.6
  package-lock.json
  package.json
Labels: renovate

#14 Update dependency vl-ui-core to v1.4.4
  package-lock.json
  package.json
Labels: renovate

#24 Update dependency vl-ui-icon to v2.0.8
  package-lock.json
  package.json
Labels: dependencies, renovate

#23 Update dependency vl-ui-core to v1.4.5
  package-lock.json
  package.json
Labels: dependencies, renovate

#22 Update dependency vl-ui-button to v1.1.6
  package-lock.json
  package.json
Labels: dependencies, renovate

#13 Update dependency np to v3.1.0
  package-lock.json
  package.json
Labels: renovate

#25 UIG-167 - Voeg issue template toe
  .dependabot/config.yml
  demo/demo.css
  demo/demo.css.map
  package-lock.json
  style.css
  style.css.map
Labels: maintenance

#26 Voeg issue templates toe
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  CODEOWNERS
  package-lock.json
  package.json
Labels: maintenance

#27 Voeg link naar issues toe aan documentatie
  vl-alert.src.js
Labels: maintenance

#28 Perform npm update --dev vl-ui-util on prepare
  package.json
Labels: enhancement
