Repository milieuinfo/webcomponent-vl-ui-alert, pull requests merged in 2020-01, with the labels that each got.

#59 Update vl-ui-util
  .vscode/launch.json
  bamboo-specs/bamboo.yml
  demo/demo.css
  demo/demo.css.map
  demo/demo.js
  package-lock.json
  package.json
  style.css
  style.css.map
  test/docker-compose.yml
  wct.docker.conf.json
  wct.local.conf.json
Labels: maintenance

#54 Toevoegen van pagina objecten
  .dependabot/config.yml
  .gitignore
  .mocharc.js
  demo/vl-alert.html
  index.js
  package-lock.json
  package.json
  test/e2e/alert.test.js
  test/e2e/components/vl-alert.js
  test/e2e/pages/vl-alert.page.js
  test/unit/vl-alert.test.html
  vl-alert.src.js
Labels: chore

#60 Update naar laatste util
  package-lock.json
  package.json
Labels: bugfix

#63 Verwijder pretest fase (installeren chromedriver). Deze komt via vl-ui-util binnenDepend op core-branch zonder after
  package.json
Labels: chore

#61 Overbodig NPM release import scripts verwijderd
  package.json
  style.css
  style.css.map
  vl-alert.js
Labels: maintenance

#62 Update vl-ui-util
  demo/demo.css
  demo/demo.css.map
  package-lock.json
  package.json
  style.css
  style.css.map
  test/docker-compose.yml
Labels: maintenance

#64 Update vl-ui-util
  bamboo-specs/bamboo.yml
  package-lock.json
  package.json
  test/docker-compose.yml
Labels: maintenance

#65 Update vl-ui-util
  bamboo-specs/bamboo.yml
  docker-compose-release.yml
  package-lock.json
  package.json
Labels: maintenance
